# Generated by Django 3.2.7 on 2021-09-27 05:44

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('calculator', '0002_alter_calculatorinfo_image'),
    ]

    operations = [
        migrations.AddField(
            model_name='calculator',
            name='slug',
            field=models.SlugField(blank=True, null=True),
        ),
    ]
