# Generated by Django 3.2.7 on 2021-09-27 06:02

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('calculator', '0003_calculator_slug'),
    ]

    operations = [
        migrations.AlterField(
            model_name='calculatorinfo',
            name='description',
            field=models.TextField(blank=True, max_length=1000, null=True),
        ),
        migrations.AlterField(
            model_name='calculatorinfo',
            name='title',
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
    ]
