# Generated by Django 3.2.7 on 2021-09-27 06:19

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('calculator', '0004_auto_20210927_0602'),
    ]

    operations = [
        migrations.AlterField(
            model_name='calculatorinfo',
            name='description',
            field=models.TextField(blank=True, max_length=2000, null=True),
        ),
    ]
