# Generated by Django 3.2.7 on 2021-09-27 06:23

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('calculator', '0005_alter_calculatorinfo_description'),
    ]

    operations = [
        migrations.AddField(
            model_name='calculatorinfo',
            name='note',
            field=models.CharField(blank=True, max_length=200, null=True),
        ),
    ]
