# Generated by Django 3.2.7 on 2021-09-27 09:20

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('calculator', '0006_calculatorinfo_note'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='calculatorinfo',
            name='image',
        ),
    ]
